on:
  pull_request:
    types: [closed]

jobs:
  lint:
    if: github.event.pull_request.merged == true
    name: Automated linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Install dependencies
        run: |
          npm install --global prettier
          composer global require friendsofphp/php-cs-fixer

      - name: Run Prettier for HTML, JavaScript, and YAML
        run: prettier --write "**/*.{html,js,yml,yaml}"

      - name: Run PHP-CS-Fixer for PHP
        run: ~/.composer/vendor/bin/php-cs-fixer fix .

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Style: Apply code formatting' || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}